language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
## This is the ugliest form of testing but since this library doesn't have proper
## tests yet, this is the best way to test that it works on a basic level.
script:  python -c "from readyfor_api import *"
script: python -m unittest
sctipt: falek8 readyfor_api/*
# Opt-in for the container-based environment
sudo: false